name: Skatteetaten on GitHub

permalink: /:title/

sass:
    sass_dir: _scss

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor
category-list:
    - Development Documentation
