title: Skatteetaten
description: on GitHub
theme: jekyll-theme-cayman

markdown: kramdown

collections:
  docs:
    output: true

menu:
  show: true

github:
  is_project_page: false

repos:
  Aurora Openshift: /aurora-openshift
  Datasamarbeid: /datasamarbeid-api-dokumentasjon
